### ISSUE TITLE
Error: Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=30s: context deadline exceeded

### ISSUE THREAD

**Issue by zhijunio** [qqshfox/cert-manager-webhook-dnspod#2]
执行安装的时候，出现下面异常，不知道你是否遇到？

Error: Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=30s: context deadline exceeded

**Comment by qqshfox** [comment]
没有碰到过类似的情况。cert-manager装了么？版本是多少？

**Comment by zhijunio** [comment]
> 没有碰到过类似的情况。cert-manager装了么？版本是多少？

已经解决了，coredns的问题
