### ISSUE TITLE
Error presenting challenge: secrets "cert-manager-webhook-dnspod-secret" not found

### ISSUE THREAD

**Issue by harvey103565** [qqshfox/cert-manager-webhook-dnspod#5]
**reproduce the bug**:
1. Install cert-manager-v0.15.1, follow [this link](https://cert-manager.io/docs/installation/kubernetes/) and install cert-> > manager using official [manifest 'cert-manager.yaml'](https://github.com/jetstack/cert-manager/releases/download/v0.15.1/cert-manager.yaml).

2. Clone this project and install webhook-dnspod using 
> ```bash
> helm install --name cert-manager-webhook-dnspod ./deploy/cert-manager-webhook-dnspod \
>    --set groupName=cert-manager.io \
>    --set secrets.apiID="my-api-id",secrets.apiToken="my-dns-token" \
>    --set clusterIssuer.enabled=true,clusterIssuer.email="my-email"
> ```

3. Create a simply ingress with 'tls' object and ‘cert-manager.io/cluster-issuer:’ annotation.

4. kubectl describe challenge -n namespace challenge-name

**To fix this bug**:
create webhook-dnspod with following instruction (with namespace specified)
> ```bash
> helm install --namespace cert-manager \
>     --name cert-manager-webhook-dnspod \
>     ./deploy/cert-manager-webhook-dnspod \
>     --set groupName=cert-manager.io \
>     --set secrets.apiID="my-api-id",secrets.apiToken="my-dns-token" \
>     --set clusterIssuer.enabled=true,clusterIssuer.email="my-email"
> ```

**Comment by qqshfox** [comment]
@harvey103565 Thank you for the feedback. Would you please create a PR to fix this issue?

**Comment by harvey103565** [comment]
Pardon, I don't use github quite often.

PR created: #8
